.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH AZR3 1 "February  24, 2010"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
azr3 \- Organ synth with distortion and rotating speakers
.SH SYNOPSIS

.B azr3 --help
.br
.B azr3 --version
.br
.B azr3 
.B [-a \fIPORT|CLIENT\fP]
.B [-j \fINAME\fP]
.B [-m \fIPORT|CLIENT\fP]
.B [-p \fINUMBER\fP]

.SH DESCRIPTION
azr3 is a port of Rumpelrausch Taips' VST plugin AZR-3 which 
simulates a drawbar organ with a distorting amplifier and a rotating speaker 
cabinet. This version is a JACK client that can be connected to any other 
MIDI and audio software using JACK.
.br

.TP
\fB -a, --audio-output\fP=\fIPORT|CLIENT\fP
When used, azr3 will try to connect its audio output ports to PORT (if it's
a JACK port name) or the first two audio input ports in CLIENT (if it's a
JACK client name).

.TP
\fB -h, --help\fP
Display a help text and exit.

.TP
\fB -j, --jack-name\fP=\fINAME\fP
Set the name of the JACK client. The default is \fBAZR-3\fP. Note that JACK may
change this name by e.g. adding a number at the end if needed.

.TP
\fB -m, --midi-input\fP=\fIPORT|CLIENT\fP

When used, azr3 will try to connect its MIDI input port to PORT (if it's a
JACK port name) or the first MIDI output port in CLIENT (if it's a JACK
client name).

.TP
\fB -p, --preset\fP=\fINUMBER\fP
Load the preset with the given number instead of the first available one.

.TP
.B -v, --version
Display version information and exit.

.P
All program options can also be set using environment variables.
The variable names are the same as the long option names with all
letters in upper case, all \fB-\fP changed to \fB_\fP and the prefix
\fBAZR3_JACK_\fP added.

Command line options override environment variables.
.SH AUTHOR
The original VST version was written by Philipp Mott, this JACK port by
Lars Luthman.
.PP
This manual page was written by Lars Luthman <lars.luthman@gmail.com>.
